version: 0.2
phases:
  install:
    runtime-versions:
      ruby: 2.6
      docker: 18
  pre_build:
    commands:
      - uname -a
      - pwd
      - ls
      - env | sort
      - ls /etc/*release*
      - cat /etc/*release*
      - whoami
      - gem install --no-document ufo
      - ECR_REPO=033484327401.dkr.ecr.us-east-1.amazonaws.com/test
      - ufo init --image $ECR_REPO --launch-type fargate --execution-role-arn arn:aws:iam::033484327401:role/service-role/codebuild-TestProject-service-role
      # - configure ~/.aws/config default
  build:
    commands:
      - echo Build started on `date`
      - echo Building project...
      - uptime
      - ufo current --service test-web
      - ufo ship
