version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - REPOSITORY_URI=033484327401.dkr.ecr.us-east-1.amazonaws.com/test
      #- COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=latest
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      #- docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      # gets the latest task definition
      - TASK_DEF=$(aws ecs describe-task-definition --task-definition "test-task")
      # gets the specific containerDefinitions array and exports to a json format which is needed for the register-task-definition function
      - CONTAINER_DEFS=$(echo $TASK_DEF | jq '.taskDefinition.containerDefinitions' | awk -v ORS= -v OFS= '{$1=$1}1')
      # creates a new task definition from the previous definition details
      - aws ecs register-task-definition --family "test-task" --container-definitions $CONTAINER_DEFS
      - aws ecs update-service --cluster webapp --service nginx --task-definition test-task
artifacts:
   files:
    - imagedefinitions.json
